
server {
    server_name seman.mesnaissances.com;

    access_log /var/log/nginx/samsam-access.log;
    error_log /var/log/nginx/samsam-error.log;

    location / {
        proxy_pass http://localhost:40081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
server {
    server_name seman.mesnaissances.com;

    access_log /var/log/nginx/samsam-access.log;
    error_log /var/log/nginx/samsam-error.log;

    location / {
        proxy_pass http://localhost:40082;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
