const APPLICATION_STATE = {
    title: "Titre par defaut",
    request: [],
    declarations: [],
}
const APPLICATION_STATE_KEY = "application-state";
const UPDATE_TITLE = "UPDATE_TITLE";
const SET_REQUESTS = "SET_REQUESTS";
const SET_REQUESTS_STATUS = "SET_REQUESTS_STATUS";
const FILTER_REQUESTS = "FILTER_REQUESTS";
const SET_TOKEN = "SET_TOKEN";
const DELETE_TOKEN = "DELETE_TOKEN";
const LOGOUT = "LOGOUT";
export { LOGOUT, APPLICATION_STATE, DELETE_TOKEN, SET_TOKEN, UPDATE_TITLE, SET_REQUESTS, SET_REQUESTS_STATUS, FILTER_REQUESTS, APPLICATION_STATE_KEY }